import { SVGElementPropMap } from "./types";

export const TYPE_MAP = {
  txt: "txt",
  html: "html",
  show: "show",
  list: "list",
  rct: "rct",
  provider: "provider",
  cmp: "cmp",
  head: "head",
} as const;

export const LW_EL_SYMBOL = Symbol.for("lw-el");

export const svgTags: (keyof SVGElementPropMap)[] = [
  "svg",
  "animate",
  "animateMotion",
  "animateTransform",
  "circle",
  "clipPath",
  "defs",
  "desc",
  "ellipse",
  "feBlend",
  "feColorMatrix",
  "feComponentTransfer",
  "feComposite",
  "feConvolveMatrix",
  "feDiffuseLighting",
  "feDisplacementMap",
  "feDistantLight",
  "feDropShadow",
  "feFlood",
  "feFuncA",
  "feFuncB",
  "feFuncG",
  "feFuncR",
  "feGaussianBlur",
  "feImage",
  "feMerge",
  "feMergeNode",
  "feMorphology",
  "feOffset",
  "fePointLight",
  "feSpecularLighting",
  "feSpotLight",
  "feTile",
  "feTurbulence",
  "filter",
  "foreignObject",
  "g",
  "image",
  "line",
  "linearGradient",
  "marker",
  "mask",
  "metadata",
  "mpath",
  "path",
  "pattern",
  "polygon",
  "polyline",
  "radialGradient",
  "rect",
  "stop",
  "switch",
  "symbol",
  "text",
  "textPath",
  "tspan",
  "use",
  "view",
];

export const SVG_MAP = svgTags.reduce((m, t) => {
  m[t] = 1;
  return m;
}, {} as Record<keyof SVGElementTagNameMap, 1>);
